DO $$
BEGIN
    TRUNCATE TABLE houses RESTART IDENTITY CASCADE;
    TRUNCATE TABLE active_seasons RESTART IDENTITY CASCADE;
    TRUNCATE TABLE actors RESTART IDENTITY CASCADE;
    TRUNCATE TABLE allies RESTART IDENTITY CASCADE;
    TRUNCATE TABLE actions RESTART IDENTITY CASCADE;
    TRUNCATE TABLE relationships RESTART IDENTITY CASCADE;
    TRUNCATE TABLE characters RESTART IDENTITY CASCADE;
END $$;