name: GOT CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils

    - name: Install dependencies and run tests
      run: mvn clean verify

    - name: Run Jacoco code coverage report
      run: mvn jacoco:report

    - name: Check code coverage threshold - should be great than 75%
      run: |
        COVERAGE=$(xmllint --xpath "number(//report/counter[@type='INSTRUCTION']/@covered)" target/site/jacoco/jacoco.xml)
        MISSED=$(xmllint --xpath "number(//report/counter[@type='INSTRUCTION']/@missed)" target/site/jacoco/jacoco.xml)
        TOTAL=$(($COVERAGE + $MISSED))
        PERCENT=$(($COVERAGE * 100 / $TOTAL))
        echo "Coverage: $PERCENT%"
        if [ "$PERCENT" -lt 75 ]; then
          echo "Code coverage is below 75%"
          exit 1
        fi

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/

    - name: Run SpotBugs analysis
      run: mvn clean compile site

    - name: Upload SpotBugs report
      uses: actions/upload-artifact@v2
      with:
        name: spotbugs-report
        path: target/site
